version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tt_hackathon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnetwork
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    networks:
      - pgnetwork
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  pgnetwork:
    driver: bridge

